### ISSUE TITLE
CLI : problem when using setup command

### ISSUE THREAD

**Issue by thomas-leroy** [mrpierrot/deckcards#1]
When runing : 
``` $ deckcards setup testCards ```

I have this result : 
``` 
/home/ME/.nvm/versions/node/v4.7.0/lib/node_modules/deckcards/lib/cli.js:12
const { readFile, parseJSON, readSpreadsheet } = require('./utils');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```
What's the required node version ?

**Comment by mrpierrot** [comment]
Hi.
Currently, I use v6.9.1

**Comment by mrpierrot** [comment]
Now, the minimal node requirement is indicated in the package.json
